language: node_js
node_js:
- node
script:
- npm run test
deploy:
  provider: npm
  email: systems@azavea.com
  api_key:
    secure: RvGHhs27KZMXQVYEksmawgzTJiBYiEUDXJX1Oed57BbGYPB+M1cdUIdm2Gh/Qw0CY8zx5pVdnsVCcGCBLV5GlZGhUPQBQLo89t7vbfTu27zGvN72BPB/UyYB5GzgDdjy35AwPDx1yvdPLTaoXMTKIsHy6ME1M6f2O4XDEfh5wHG4hffVeq7hklKER5+xLCo9aOWfb23qNTjfDPRWRXbfdU+PuLKJ6JzIHnh9zLTCXmCrv++vVDfVZZPdMQvErFlaXfDKwTBgCbxbYQz/i4gZz00OZddp9CsmBLeHgoSFSscoHg0qzfVKmccDQ3BaaMew2yxxfVKXA7XI60GJO9i5wsuKHW6mcXLaTCCYIvEowDJAUBRbawLAIEsEy/IFH8+e1EPUIcJpNgqSQlvpdsuMyPMx60WYMBbLX1Rn46wAIohtXp3Foqg8ArkFNIrsCFLuaINP4Bh5Puqqi5EzyLyWg2+gJ/5Z8V58vJ5z+fRWIbBH1APby3o9vO8Dnv+lw7EJJrPVnWkexAEVUGq5TXLYxV9xV33OG8kjeu51EaEWsNLFncVdINmR20RKZv8yWTGaiY0PuqdVINpnwhhrqSx7p/jg8xZ21V6zrrpo2L5j/v6dA9rmwLPWzc7EJLBEymChPda4o1jnJZMBctBJvETarTy1Gqh4yG3EZwSsR/sK6PE=
  on:
    tags: true
    repo: azavea/tilejson-validator
