language: node_js
node_js:
- node
script:
- npm run test
deploy:
  provider: npm
  email: systems@azavea.com
  api_key: lN8T7F1tqxvHMXogsHo1b5ctV7Dl/OtF4luabSMRphoYXLdAwCtQOVx7smpmEwKN+IR82EvasLmEMtKTopbPX2CQqWohqWzfPjMZq/TJF6oqHe3A2HT6gj4vNPfqr6u77f6VRskgIm5YrbhJJ5JEQAQES5gUmRdIFuwEMgSEezPx/6Qya3RegRDVdx1P4N64ofnEmkAf2GixIwJTJzxoknZ/z7EzcXVIB1zQ6+Eq6Axbm8KdYHhPjCx4x/M2fbnb3i9mJZiYgD2ULsq9h0EyXvwf06vpQ+jFaDExmoSmeiXk9HepbclN4yTAiJvP+lhPp0L+82gOm6rUyDxSkoenAUL4RBFQ0asiksDdr0YO9z+V9YAC1I7FYyEn06gTVeQcD94cyKtmZxsDUYNXhUjbbvUUutJaRp3W7skEnTu0JDtBi360BO/pOG/8mmDuNQY3VturYpCioT87dTxXzVcU+I0fnUEy0R0nc9/lKqe91g3od/PU5BAgHjjPJbHXdZcUWwDKw1Mq79tbxWBUNP1qTFgUVFDg8iJDabhpX491tnZ1bAd8COvJjmMimCgYHWk7KVkMpv7drgrslMcsj4ytPMjlRC/zRQT0jjmT30oa4SG+PJD6y7xnM+s3P9wjtcxuBw/KlgNvFsdtGTh7Hz0G7z4i55ElrAxc7iCmEtxiiVg=
  on:
    tags: true
